# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c162b0613e8c2b8e82e8d74b754f99895aa826072aa9c5ef5d24f61b8ad769ecac0bcfab55359248eec39efaf37cbecc56f76e75644a93a9a0a560cf1e8406ec

test:
  secret_key_base: d1d4b903c63d4440aaab3fdae20d51d34495a871b2aa30083b2c0b0d835566f5592db509725a795d6da64ff3806f917094ed4e26452ffd97aaae5028bf58336c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
